export const PROJECT_NAME = "Project Vanguard";
export const MISSION_NAME = "Salto 1";
export const REPOSITORY_URL = "https://github.com/Thought-ed/capstone-project";

export const DASHBOARD_SECTIONS = [
  {
    id: "overview",
    navLabel: "Mission Dashboard",
    shortLabel: "MD",
    eyebrow: "Salto 1 Control",
    title: MISSION_NAME,
    summary: `${PROJECT_NAME} mission control for the capstone rocketry workspace.`,
    detail: "Organized dashboard shell, modular auth flow, and sectioned mission views.",
    heroImage: "./logo.png",
    stats: [
      { label: "State", value: "Structured" },
      { label: "Phase", value: "Planning" },
      { label: "Focus", value: "Refactor" },
    ],
    cards: [
      {
        kind: "status",
        title: "Current State",
        value: "Dashboard shell",
        detail: "Auth gate, sidebar navigation, and mission sections are wired.",
        progress: 58,
        width: "wide",
      },
      {
        kind: "contacts",
        title: "Key Contacts",
        width: "third",
        people: [
          { name: "Dr. Camilo Rivera", role: "Faculty Advisor", email: "crivera@school.edu.co" },
          { name: "Mario Jose Gomez", role: "Team Lead", email: "mjgomez@school.edu.co" },
          { name: "Juan Esteban Ruiz", role: "Avionics Lead", email: "jruiz@school.edu.co" },
        ],
      },
      {
        kind: "list",
        title: "Launch Readiness Tracker",
        width: "half",
        items: [
          { label: "Flight hardware assembly complete", meta: "done", tone: "good" },
          { label: "Recovery system test x2", meta: "done", tone: "good" },
          { label: "Motor received and inspected", meta: "done", tone: "good" },
          { label: "Avionics functional test", meta: "pending", tone: "neutral" },
          { label: "Pre-launch safety review", meta: "pending", tone: "neutral" },
        ],
      },
      {
        kind: "list",
        title: "Upcoming Deadlines",
        width: "half",
        items: [
          { label: "PDR presentation", meta: "May 30, 2026", tone: "warn" },
          { label: "Budget report · Phase 2", meta: "June 4, 2026", tone: "info" },
          { label: "Recovery integration test", meta: "June 8, 2026", tone: "info" },
          { label: "Launch checklist review", meta: "June 12, 2026", tone: "warn" },
        ],
      },
      {
        kind: "list",
        title: "Active Risks",
        width: "half",
        items: [
          { label: "Parachute deployment delay", meta: "Critical", tone: "critical" },
          { label: "Ejection charge inconsistency", meta: "High", tone: "warn" },
          { label: "Telemetry data loss", meta: "High", tone: "warn" },
        ],
      },
      {
        kind: "links",
        title: "Quick Links",
        width: "third",
        links: [
          { label: "Tasks Kanban Board", href: "#" },
          { label: "Milestones Timeline", href: "#" },
          { label: "Risk Register", href: "#" },
          { label: "Launch Checklist", href: "#" },
        ],
      },
    ],
  },
  {
    id: "propulsion",
    navLabel: "Propulsion",
    shortLabel: "PR",
    eyebrow: "Engineering System",
    title: "Propulsion",
    summary: "Motor selection, thrust curve tracking, and test readiness.",
    detail: "Commercial motor planning and propulsion test coordination.",
    heroImage: "./logo.png",
    stats: [
      { label: "Motor", value: "Selected" },
      { label: "Tests", value: "2 queued" },
      { label: "Risk", value: "Medium" },
    ],
    cards: [
      {
        kind: "status",
        title: "Motor Shortlist",
        value: "2 options",
        detail: "Estes and AeroTech class motors under review.",
        progress: 68,
        width: "half",
      },
      {
        kind: "list",
        title: "Test Log",
        width: "half",
        items: [
          { label: "Static thrust comparison", meta: "Scheduled", tone: "info" },
          { label: "Mass budget validation", meta: "In review", tone: "neutral" },
          { label: "Motor mount fit check", meta: "Complete", tone: "good" },
        ],
      },
      {
        kind: "links",
        title: "Reference Files",
        width: "third",
        links: [
          { label: "OpenRocket model", href: "#" },
          { label: "Thrust curve notes", href: "#" },
        ],
      },
    ],
  },
  {
    id: "airframe",
    navLabel: "Airframe",
    shortLabel: "AF",
    eyebrow: "Engineering System",
    title: "Airframe",
    summary: "Structure, stability, and payload accommodation.",
    detail: "Airframe geometry and CAD review for launch readiness.",
    heroImage: "./logo.png",
    stats: [
      { label: "CAD", value: "Drafted" },
      { label: "Mass", value: "Tracked" },
      { label: "Stability", value: "Nominal" },
    ],
    cards: [
      {
        kind: "list",
        title: "Structural Checks",
        width: "half",
        items: [
          { label: "Fin alignment review", meta: "Pending", tone: "neutral" },
          { label: "Body tube reinforcement", meta: "Planned", tone: "info" },
          { label: "Payload bay fit", meta: "Complete", tone: "good" },
        ],
      },
      {
        kind: "status",
        title: "CAD Progress",
        value: "78%",
        detail: "Model ready for peer review and assembly cross-checks.",
        progress: 78,
        width: "half",
      },
      {
        kind: "links",
        title: "Documentation",
        width: "third",
        links: [
          { label: "Dimension set", href: "#" },
          { label: "Assembly notes", href: "#" },
        ],
      },
    ],
  },
  {
    id: "recovery",
    navLabel: "Recovery",
    shortLabel: "RC",
    eyebrow: "Engineering System",
    title: "Recovery",
    summary: "Parachute deployment, ejection checks, and landing safety.",
    detail: "Recovery subsystem validation and deployment sequencing.",
    heroImage: "./logo.png",
    stats: [
      { label: "Deployment", value: "Testing" },
      { label: "Canopy", value: "Selected" },
      { label: "Risk", value: "High" },
    ],
    cards: [
      {
        kind: "status",
        title: "Deployment Confidence",
        value: "66%",
        detail: "Ground tests are increasing confidence before flight day.",
        progress: 66,
        width: "wide",
      },
      {
        kind: "list",
        title: "Recovery Checks",
        width: "half",
        items: [
          { label: "Parachute fold sequence", meta: "Complete", tone: "good" },
          { label: "Shock cord inspection", meta: "Complete", tone: "good" },
          { label: "Ejection charge timing", meta: "In test", tone: "warn" },
        ],
      },
      {
        kind: "links",
        title: "Evidence",
        width: "third",
        links: [
          { label: "Drop test clips", href: "#" },
          { label: "Recovery checklist", href: "#" },
        ],
      },
    ],
  },
  {
    id: "avionics",
    navLabel: "Avionics",
    shortLabel: "AV",
    eyebrow: "Engineering System",
    title: "Avionics",
    summary: "Altimeter, logging, and wiring integrity.",
    detail: "Flight electronics and recovery trigger system coordination.",
    heroImage: "./logo.png",
    stats: [
      { label: "Altimeter", value: "Ready" },
      { label: "Wiring", value: "Routing" },
      { label: "Logs", value: "Queued" },
    ],
    cards: [
      {
        kind: "list",
        title: "Hardware Status",
        width: "half",
        items: [
          { label: "Altimeter bench test", meta: "Complete", tone: "good" },
          { label: "Battery pack review", meta: "Pending", tone: "neutral" },
          { label: "Recovery output continuity", meta: "Scheduled", tone: "info" },
        ],
      },
      {
        kind: "status",
        title: "Integration Readiness",
        value: "54%",
        detail: "Wiring layout is mapped and bench verification is next.",
        progress: 54,
        width: "half",
      },
      {
        kind: "links",
        title: "Files",
        width: "third",
        links: [
          { label: "Wiring diagram", href: "#" },
          { label: "Sensor checklist", href: "#" },
        ],
      },
    ],
  },
  {
    id: "simulation",
    navLabel: "Simulation",
    shortLabel: "SIM",
    eyebrow: "Analysis",
    title: "Simulation & Analysis",
    summary: "OpenRocket and RASAero planning for launch predictions.",
    detail: "Trajectory models and sensitivity review for flight planning.",
    heroImage: "./logo.png",
    stats: [
      { label: "Model", value: "OpenRocket" },
      { label: "Validation", value: "Ongoing" },
      { label: "Risk", value: "Medium" },
    ],
    cards: [
      {
        kind: "status",
        title: "Simulation Coverage",
        value: "81%",
        detail: "Flight and recovery estimates are aligned with hardware assumptions.",
        progress: 81,
        width: "half",
      },
      {
        kind: "list",
        title: "Analysis Queue",
        width: "half",
        items: [
          { label: "Stability margin sweep", meta: "In progress", tone: "info" },
          { label: "Apogee sensitivity", meta: "Scheduled", tone: "neutral" },
          { label: "Wind drift estimate", meta: "Pending", tone: "neutral" },
        ],
      },
      {
        kind: "links",
        title: "Models",
        width: "third",
        links: [
          { label: "OpenRocket file", href: "#" },
          { label: "RASAero notes", href: "#" },
        ],
      },
    ],
  },
  {
    id: "safety",
    navLabel: "Safety",
    shortLabel: "SF",
    eyebrow: "Compliance",
    title: "Safety & Compliance",
    summary: "Launch field, regulations, and procedural readiness.",
    detail: "Checklist-driven planning for field permissions and safety steps.",
    heroImage: "./logo.png",
    stats: [
      { label: "Checklist", value: "Active" },
      { label: "Field", value: "Pending" },
      { label: "Risk", value: "Critical" },
    ],
    cards: [
      {
        kind: "list",
        title: "Safety Review",
        width: "wide",
        items: [
          { label: "Launch permissions", meta: "Pending", tone: "warn" },
          { label: "Field inspection", meta: "Pending", tone: "warn" },
          { label: "Fire suppression gear", meta: "Checked", tone: "good" },
          { label: "Weather monitoring", meta: "Required", tone: "info" },
        ],
      },
      {
        kind: "links",
        title: "Compliance Files",
        width: "third",
        links: [
          { label: "Safety checklist", href: "#" },
          { label: "Field briefing", href: "#" },
        ],
      },
    ],
  },
  {
    id: "management",
    navLabel: "Project Management",
    shortLabel: "PM",
    eyebrow: "Operations",
    title: "Project Management",
    summary: "Tasks, milestones, meeting notes, and sprint planning.",
    detail: "Team coordination and deliverable tracking in one place.",
    heroImage: "./logo.png",
    stats: [
      { label: "Tasks", value: "24 open" },
      { label: "Milestones", value: "5 active" },
      { label: "Meetings", value: "Weekly" },
    ],
    cards: [
      {
        kind: "list",
        title: "Sprint Board",
        width: "half",
        items: [
          { label: "CAD cleanup", meta: "In progress", tone: "info" },
          { label: "Budget update", meta: "Pending", tone: "neutral" },
          { label: "Review notes", meta: "Scheduled", tone: "neutral" },
        ],
      },
      {
        kind: "list",
        title: "Recent Meeting Notes",
        width: "half",
        items: [
          { label: "Weekly sync · May 9", meta: "Follow-ups assigned", tone: "good" },
          { label: "Design review · May 2", meta: "Actions captured", tone: "good" },
          { label: "Safety review · Apr 25", meta: "Compliance updated", tone: "good" },
        ],
      },
      {
        kind: "links",
        title: "Board Links",
        width: "third",
        links: [
          { label: "Tasks", href: "#" },
          { label: "Milestones", href: "#" },
          { label: "Meeting notes", href: "#" },
        ],
      },
    ],
  },
  {
    id: "deliverables",
    navLabel: "Academic & Deliverables",
    shortLabel: "DL",
    eyebrow: "Deliverables",
    title: "Academic & Deliverables",
    summary: "Report drafts, presentation assets, and grading evidence.",
    detail: "Everything needed for the final booth, report, and evidence trail.",
    heroImage: "./logo.png",
    stats: [
      { label: "Report", value: "Drafting" },
      { label: "Presentation", value: "Queued" },
      { label: "Evidence", value: "Collecting" },
    ],
    cards: [
      {
        kind: "list",
        title: "Deliverable Checklist",
        width: "half",
        items: [
          { label: "Technical report", meta: "Draft", tone: "info" },
          { label: "Presentation deck", meta: "Planned", tone: "neutral" },
          { label: "Physical evidence set", meta: "Collecting", tone: "warn" },
        ],
      },
      {
        kind: "links",
        title: "Assets",
        width: "half",
        links: [
          { label: "Report draft", href: "#" },
          { label: "Booth visuals", href: "#" },
          { label: "Grading rubric", href: "#" },
        ],
      },
    ],
  },
  {
    id: "github",
    navLabel: "GitHub Repository",
    shortLabel: "GH",
    eyebrow: "Version Control",
    title: "GitHub Repository",
    summary: `${PROJECT_NAME} source, history, and collaboration live here.`,
    detail: `The branch, issues, and pull request workflow for ${PROJECT_NAME}.`,
    heroImage: "./logo.png",
    stats: [
      { label: "Commits", value: "128" },
      { label: "Branches", value: "7" },
      { label: "Pull Requests", value: "12" },
    ],
    cards: [
      {
        kind: "repository",
        title: "Repository Summary",
        width: "wide",
        repoName: "thought-ed/capstone-project",
        repoDescription: "Simulation files, docs, CAD, and code for Project Vanguard.",
        stats: [
          { label: "Commits", value: "128" },
          { label: "Branches", value: "7" },
          { label: "PRs", value: "12" },
          { label: "Contributors", value: "4" },
        ],
      },
      {
        kind: "links",
        title: "Repository Links",
        width: "third",
        links: [
          { label: "Open repository", href: REPOSITORY_URL },
          { label: "Issues", href: "#" },
          { label: "Pull requests", href: "#" },
        ],
      },
    ],
  },
];
